name: 'Pull Request'
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  pull-request:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2

        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@2654679fe7f7c29875c669398a8ec0791b8a64a1  # 1.215.0
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Test Site
        run: bash tools/test.sh
        env:
          JEKYLL_ENV: production

